name: Docker Deployment CD

on:
  workflow_run:
    workflows: ['Docker Image CI']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Deploy docker image
        run: sudo docker pull mariachakhtoura/employee-directory-services:latest
      - name: Delete old docker container
        run: sudo docker rm -f employee-directory-services-container || true
      - name: Run docker container
        run: sudo docker run -d -p 3000 --name employee-directory-services-container mariachakhtoura/employee-directory-services
